### ISSUE TITLE
controls mess

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_snip_to_call#4]
![kv](https://cloud.githubusercontent.com/assets/4154978/16918228/c86b5c0c-4d15-11e6-94d3-671362e344bf.png)

**Comment by kvichans** [comment]
Вижу две проблемы
1. Редакторы налезли на listview
2. Текст "OR" не выровнен с текстом "In Snip"

Первая лечится легко.
Вторая потребует организации хака. Уже придумал как это сделать - будет диалог, в котором можно будет подстраивать под **текущую** платформу сдвиговые (хаковые) поправки для выравнивания контролов. Часть таких поправок уже встроено в `wrapper`, остальные будут сохраняться в `user.json`. Если эти поправки станут известны мне - добавлю их в `wrapper`.
